version: '3.6'
services:
  text_classification_grievance_recognition:
    container_name: text_classification_grievance_recognition
    image: ghcr.io/samagra-development/ai-tools/text_classification_grievance_recognition:latest
    restart: always
    ports:
      - "8003:5000"
    env_file:
      - ./.env
