version: '3.6'
services:
  ts-cache:
    container_name: ts-cache
    image: redis:latest
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.3.1.6:12201"
        tag: ts-cache
    environment:
      REDIS_HOST: "10.3.1.6"
      REDIS_PORT: "6379"
      SERVER_PORT: "3000"
      ADAPTER_URL: "10.3.1.6:8081"
      JWKS_URI: "http://10.3.1.6:9011/.well-known/jwks.json"
    ports:
      - '6379:6379'
    command: [ 'redis-server', '--appendonly', 'yes' ]
    hostname: redis
    volumes:
      - redis_data:/data
      - redis_conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
  redis_conf:
