version: '3.6'
services:
  fusionauth_db:
    image: postgres:12.9
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.3.1.6:12201"
        tag: fusionauth_db
    volumes:
      - fusionauth_pgdata:/var/lib/postgresql/data

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: fusionauth_search
    ports:
      - "9200:9200"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.3.1.6:12201"
        tag: search
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--write-out",
          "'HTTP %{http_code}'",
          "--silent",
          "--output",
          "/dev/null",
          "http://localhost:9200/"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - fustionauth_search_data:/usr/share/elasticsearch/data

volumes:
  fusionauth_pgdata:

  fustionauth_search_data: