global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'FID'
    static_configs:
      - targets: ['bff:3000']
  
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']