version: '3.6'
services:
  bff_timescaledb:
    container_name: bff_timescaledb
    image: samagragovernance/postgres:latest-pg15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - bff_pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  agrimitra-nginx:
    depends_on:
      - bff
    container_name: agrimitra-nginx
    build:
      context: ./nginx
    network_mode: "host"

  bff:
    container_name: bff
    depends_on:
      - bff_timescaledb
    image: ghcr.io/agri-mitra/bff:main
    restart: always
    ports:
      - "8081:3000"
    env_file:
      - ./.env

  text_classification_grievance_recognition:
    container_name: text_classification_grievance_recognition
    image: ghcr.io/samagra-development/ai-tools/text_classification_grievance_recognition:latest
    restart: always
    ports:
      - "8000:8000"

volumes:
  bff_pgdata:
